//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by STX.rc
//
#define IDM_ABOUT_DIALOG                0x0010
#define IDD_ABOUT_DIALOG                100
#define IDD_STX_DIALOG                  102
#define IDR_MAINFRAME                   128
#define IDC_LABEL_STX                   1001
#define IDC_STX_FILE                    1002
#define IDC_BROWSE_STX                  1003
#define IDC_LABEL_KSFFOLDER             1004
#define IDC_KSF_FOLDER                  1005
#define IDC_BROWSE_KSF                  1006
#define IDC_TITLE_MODES                 1007
#define IDC_BUTTON_DEFAULT_FILENAMES    1008
#define IDC_BUTTON_KIU                  1009
#define IDC_BUTTON_DM                   1010
#define IDC_BUTTON_SELECTALL            1011
#define IDC_BUTTON_CRAZY                1012
#define IDC_CHECK_PRACTICE              1013
#define IDC_CHECK_NORMAL                1014
#define IDC_CHECK_HARD                  1015
#define IDC_CHECK_NIGHTMARE             1016
#define IDC_CHECK_CRAZY                 1017
#define IDC_CHECK_FULLDOUBLE            1018
#define IDC_CHECK_HALFDOUBLE            1019
#define IDC_CHECK_DIVISION              1020
#define IDC_CHECK_LIGHTMAP              1021
#define IDC_DIFFICULTY_PRACTICE         1022
#define IDC_DIFFICULTY_NORMAL           1023
#define IDC_DIFFICULTY_HARD             1024
#define IDC_DIFFICULTY_NIGHTMARE        1025
#define IDC_DIFFICULTY_CRAZY            1026
#define IDC_DIFFICULTY_FULLDOUBLE       1027
#define IDC_DIFFICULTY_HALFDOUBLE       1028
#define IDC_DIFFICULTY_DIVISION         1029
#define IDC_DIFFICULTY_LIGHTMAP         1030
#define IDC_FILENAME_PRACTICE           1031
#define IDC_FILENAME_NORMAL             1032
#define IDC_FILENAME_HARD               1033
#define IDC_FILENAME_NIGHTMARE          1034
#define IDC_FILENAME_CRAZY              1035
#define IDC_FILENAME_FULLDOUBLE         1036
#define IDC_FILENAME_HALFDOUBLE         1037
#define IDC_FILENAME_DIVISION           1038
#define IDC_FILENAME_LIGHTMAP           1039
#define IDC_TITLE_STXINFO               1040
#define IDC_LABEL_ARTIST                1041
#define IDC_TEXT_ARTIST                 1042
#define IDC_LABEL_SONG                  1043
#define IDC_TEXT_SONG                   1044
#define IDC_LABEL_AUTHOR                1045
#define IDC_TEXT_AUTHOR                 1046
#define IDC_TITLE_OPTIONS               1047
#define IDC_CHECK_OVERWRITE             1048
#define IDC_CHECK_SYNCRO                1049
#define IDC_BUTTON_ADV_OPTIONS          1050
#define IDC_CONVERTFILE                 1051
#define IDC_BATCHMODE                   1052
#define IDC_LABEL_STX2DM                1053
#define IDC_LABEL_ALDONIO               1054
#define IDC_LABEL_THANKS                1055
#define IDS_OK                          2000
#define IDS_LABEL_STX                   2001
#define IDS_STX_FILE                    2002
#define IDS_BROWSE_STX                  2003
#define IDS_LABEL_KSFFOLDER             2004
#define IDS_KSF_FOLDER                  2005
#define IDS_BROWSE_KSF                  2006
#define IDS_TITLE_MODES                 2007
#define IDS_BUTTON_DEFAULT_FILENAMES    2008
#define IDS_BUTTON_KIU                  2009
#define IDS_BUTTON_DM                   2010
#define IDS_BUTTON_SELECTALL            2011
#define IDS_BUTTON_CRAZY                2012
#define IDS_CHECK_PRACTICE              2013
#define IDS_CHECK_NORMAL                2014
#define IDS_CHECK_HARD                  2015
#define IDS_CHECK_NIGHTMARE             2016
#define IDS_CHECK_CRAZY                 2017
#define IDS_CHECK_FULLDOUBLE            2018
#define IDS_CHECK_HALFDOUBLE            2019
#define IDS_CHECK_DIVISION              2020
#define IDS_CHECK_LIGHTMAP              2021
#define IDS_DIFFICULTY_PRACTICE         2022
#define IDS_DIFFICULTY_NORMAL           2023
#define IDS_DIFFICULTY_HARD             2024
#define IDS_DIFFICULTY_NIGHTMARE        2025
#define IDS_DIFFICULTY_CRAZY            2026
#define IDS_DIFFICULTY_FULLDOUBLE       2027
#define IDS_DIFFICULTY_HALFDOUBLE       2028
#define IDS_DIFFICULTY_DIVISION         2029
#define IDS_DIFFICULTY_LIGHTMAP         2030
#define IDS_FILENAME_PRACTICE           2031
#define IDS_FILENAME_NORMAL             2032
#define IDS_FILENAME_HARD               2033
#define IDS_FILENAME_NIGHTMARE          2034
#define IDS_FILENAME_CRAZY              2035
#define IDS_FILENAME_FULLDOUBLE         2036
#define IDS_FILENAME_HALFDOUBLE         2037
#define IDS_FILENAME_DIVISION           2038
#define IDS_FILENAME_LIGHTMAP           2039
#define IDS_TITLE_STXINFO               2040
#define IDS_LABEL_ARTIST                2041
#define IDS_TEXT_ARTIST                 2042
#define IDS_LABEL_SONG                  2043
#define IDS_TEXT_SONG                   2044
#define IDS_LABEL_AUTHOR                2045
#define IDS_TEXT_AUTHOR                 2046
#define IDS_TITLE_OPTIONS               2047
#define IDS_CHECK_OVERWRITE             2048
#define IDS_CHECK_SYNCRO                2049
#define IDS_BUTTON_ADV_OPTIONS          2050
#define IDS_CONVERTFILE                 2051
#define IDS_BATCHMODE                   2052
#define IDS_LABEL_STX2DM                2053
#define IDS_LABEL_ALDONIO               2054
#define IDS_LABEL_THANKS                2055
#define IDS_SUCCESS                     2056
#define IDS_HALF_SUCCESS                2057
#define IDS_NO_SUCCESS                  2058
#define IDS_ABOUTBOX                    3001
#define IDS_STX_DIALOG                  3002
#define IDS_ABOUT_DIALOG                3003
#define IDS_KIU_FILENAME_NORMAL         3004
#define IDS_KIU_FILENAME_HARD           3005
#define IDS_KIU_FILENAME_NIGHTMARE      3006
#define IDS_KIU_FILENAME_CRAZY          3007
#define IDS_KIU_FILENAME_FULLDOUBLE     3008
#define IDS_KIU_FILENAME_HALFDOUBLE     3009
#define IDS_DM_FILENAME_PRACTICE        3010
#define IDS_DM_FILENAME_NORMAL          3011
#define IDS_DM_FILENAME_HARD            3012
#define IDS_DM_FILENAME_NIGHTMARE       3013
#define IDS_DM_FILENAME_CRAZY           3014
#define IDS_DM_FILENAME_FULLDOUBLE      3015
#define IDS_DM_FILENAME_HALFDOUBLE      3016
#define IDS_DM_FILENAME_DIVISION        3017
#define IDS_FILE_STX                    3018
#define IDS_FILE_ALL                    3019
#define IDS_BROWSE                      3020
#define IDS_BROWSEFORSTX                3021
#define IDS_ERROR_INVALIDSTX            4001
#define IDS_ERROR_CANTOPEN              4002
#define IDS_ERROR_NOTSTX                4003
#define IDS_ERROR_NOFOLDER              4004
#define IDS_ERROR_NOMODES               4005
#define IDS_ERROR_EMPTYFILENAME         4006
#define IDS_ERROR_NOARTIST              4007
#define IDS_ERROR_NOSONG                4008
#define IDS_ERROR_CANTSAVE              4009
#define IDS_ERROR_NOFOLDERSTX           4010

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1053
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
